/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

// lembrar: Faça comentários nas classes para explicar o que os métodos fazem e o que os atributos significam.

import edu.princeton.cs.algs4.Draw;
import java.awt.*;

public class App {
    private Draw draw;

    public App() {
        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000, 600);
        this.draw.setXscale(0, 1000);
        this.draw.setYscale(0, 600);

    }

    // main
    public static void main(String[] args) {
        App app = new App();
        app.draw.show();
        Grade grade = new Grade(app.draw);
        grade.desenharGrade(app.draw);
//        Grade tabuleiro = new Grade(draw);
//        tabuleiro.desenharGrade(draw);
//        draw.show();

    }
}
